matrix:
  include:
  - language: node_js
    env: COMMAND=frontend
    node_js:
    - stable
    cache:
      npm: true
    before_install:
    - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(frontend/||\.travis.yml)' || travis_terminate 0
    - cd frontend
    install:
    - npm install
    - npm install react-scripts@3.0.1
    script:
    - npm run build
    deploy:
    - provider: heroku
      api_key:
        secure: S+mWPtKv1KORTp84jXWAqBkrAOhYB6X4x2QZ/FR+ez1SzBfxxCsdLi/PWKNEzC/TRGdhrgkPTgFFsGuNpw6GEwkO1ON3pfIccqRFGAbMEb7QmIDV+DrulikCT44rTqE9anBo30jvhsDyiEC5WuLF7ziRzGEYLq0rNg+axr6cvGx207YBRVZ46yVskbcl6VFvtT2q8h6YuFReFgWKMjJ5ZOi/eoSwV/W1FKFsWJ4j15pi9SP5GfOx2bcPiHL9fKCpafrt89aGq7+RP8aFyByQipAgtpL6kPYegwfG4K3URQRVXYGFp8qyAv+x150vl8O9snl6/Mmc4Ay9qCLZQFYJLTlgqwBK9slMonuz/ATrkvaM9wR0h4uuieei5yPvGyMHzCc+E5v3497Kx5MR2qJBrn8w045VbgH9+zIl+Z5kRDi3LWnI4tdZVBmFNbGp0k5Wj43qgArUlg/CBhjTbhHwxiKYjICm6PmWMc4Nu7r3Z9SjBrRdyPXW0pHK2vp1p21GWXRV0FaNsGcltQy5AdCUHkUkYG82OIafc7seVTf2cHbkVc8GpyH0qdbRfe3OKgZFSxX8R6dBaBn0WhhDNQWEvDKoEQqkxgmHsj6UlDDug054JXdRWlw/QuXmy9PKFB3vVwFNSCr55ALA5Ei4735YYeupxZ0+OntQR/zG1kaQexg=
      app:
        master: cheatsheet-generator-web-test
  - language: node_js
    env: COMMAND=backend
    node_js:
    - stable
    cache:
      npm: true
    before_install:
    - git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qE '^(backend/||\.travis.yml)' || travis_terminate 0
    - cd backend
    install:
    - npm install
    deploy:
    - provider: heroku
      api_key:
        secure: S+mWPtKv1KORTp84jXWAqBkrAOhYB6X4x2QZ/FR+ez1SzBfxxCsdLi/PWKNEzC/TRGdhrgkPTgFFsGuNpw6GEwkO1ON3pfIccqRFGAbMEb7QmIDV+DrulikCT44rTqE9anBo30jvhsDyiEC5WuLF7ziRzGEYLq0rNg+axr6cvGx207YBRVZ46yVskbcl6VFvtT2q8h6YuFReFgWKMjJ5ZOi/eoSwV/W1FKFsWJ4j15pi9SP5GfOx2bcPiHL9fKCpafrt89aGq7+RP8aFyByQipAgtpL6kPYegwfG4K3URQRVXYGFp8qyAv+x150vl8O9snl6/Mmc4Ay9qCLZQFYJLTlgqwBK9slMonuz/ATrkvaM9wR0h4uuieei5yPvGyMHzCc+E5v3497Kx5MR2qJBrn8w045VbgH9+zIl+Z5kRDi3LWnI4tdZVBmFNbGp0k5Wj43qgArUlg/CBhjTbhHwxiKYjICm6PmWMc4Nu7r3Z9SjBrRdyPXW0pHK2vp1p21GWXRV0FaNsGcltQy5AdCUHkUkYG82OIafc7seVTf2cHbkVc8GpyH0qdbRfe3OKgZFSxX8R6dBaBn0WhhDNQWEvDKoEQqkxgmHsj6UlDDug054JXdRWlw/QuXmy9PKFB3vVwFNSCr55ALA5Ei4735YYeupxZ0+OntQR/zG1kaQexg=
      app:
        master: cheatsheet-generator-app-test
