version: '3'
services:
  web:
    build: ./frontend
    container_name: frontend
    volumes:
      - './frontend:/web'
      - '/web/node_modules'
    ports:
      - '3000:3000'
  app:
    environment:
      - CHEATSHEET_GENERATOR_CLIENT_URL=http://web:3000
    build: ./backend
    container_name: backend
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    ports:
      - '8000:8000'
